[package]
name = "deadman-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
libadwaita = "0.8.0"
tracing = "0.1.37"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.16"
deadman-ipc = { path = "../deadman-ipc" }
rusb = "0.8"