[package]
name = "deadmand"
version = "0.1.0"
edition = "2024"

[dependencies]

deadman-ipc = { path = "../deadman-ipc" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rusb = "0.8.0"
